# Generated by Django 2.2.12 on 2020-05-13 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ff_api.fields.db
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('nconst', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('primaryName', models.CharField(max_length=255)),
                ('birthYear', models.IntegerField()),
                ('deathYear', models.IntegerField(null=True)),
                ('primaryProfession', ff_api.fields.db.SeparatedValuesField()),
                ('knownForTitles', ff_api.fields.db.SeparatedValuesField()),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('tconst', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titleType', models.CharField(max_length=255)),
                ('primaryTitle', models.CharField(max_length=255)),
                ('originalTitle', models.CharField(max_length=255)),
                ('isAdult', models.CharField(max_length=1)),
                ('startYear', models.CharField(max_length=4)),
                ('endYear', models.CharField(max_length=4, null=True)),
                ('runtimeMinutes', models.CharField(max_length=10)),
                ('genres', ff_api.fields.db.SeparatedValuesField()),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now_add=True)),
                ('updated', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now_add=True)),
                ('updated', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averageRating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numVotes', models.IntegerField()),
                ('tconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff_api.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255, null=True)),
                ('characters', models.TextField(null=True)),
                ('nconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff_api.Name')),
                ('tconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff_api.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now_add=True)),
                ('updated', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentTconst', models.CharField(max_length=255)),
                ('seasonNumber', models.IntegerField(null=True)),
                ('episodeNumber', models.IntegerField(null=True)),
                ('tconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff_api.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directors', ff_api.fields.db.SeparatedValuesField()),
                ('writers', ff_api.fields.db.SeparatedValuesField()),
                ('tconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff_api.Title')),
            ],
        ),
    ]
