# Generated by Django 2.2.12 on 2020-05-13 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='name',
            name='knownForTitles',
        ),
        migrations.AddField(
            model_name='name',
            name='knownForTitles',
            field=models.ManyToManyField(blank=True, null=True, to='ff_api.Title'),
        ),
        migrations.RemoveField(
            model_name='title',
            name='genres',
        ),
        migrations.AddField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(to='ff_api.Genre'),
        ),
    ]
