# Generated by Django 2.2.12 on 2020-05-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0003_auto_20200513_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='birthYear',
            field=models.IntegerField(null=True),
        ),
    ]
