# Generated by Django 2.2.12 on 2020-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0004_auto_20200513_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='directors',
        ),
        migrations.AddField(
            model_name='crew',
            name='directors',
            field=models.ManyToManyField(related_name='directors', to='ff_api.Name'),
        ),
        migrations.RemoveField(
            model_name='crew',
            name='writers',
        ),
        migrations.AddField(
            model_name='crew',
            name='writers',
            field=models.ManyToManyField(related_name='writers', to='ff_api.Name'),
        ),
    ]
