# Generated by Django 2.2.12 on 2020-05-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0005_auto_20200513_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ff_api.Title', verbose_name='tconst'),
            preserve_default=False,
        ),
    ]
