# Generated by Django 2.2.12 on 2020-05-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0006_favourite_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='seen',
            name='title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ff_api.Title', verbose_name='tconst'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ff_api.Title', verbose_name='tconst'),
            preserve_default=False,
        ),
    ]
