# Generated by Django 2.2.12 on 2020-05-14 10:00

from django.db import migrations
import ff_api.fields.db


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0007_auto_20200514_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='primaryProfession',
            field=ff_api.fields.db.SeparatedValuesField(default=''),
        ),
    ]
