# Generated by Django 2.2.12 on 2020-05-14 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ff_api.fields.db
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ff_api', '0010_favouritegenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDbTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now_add=True)),
                ('updated', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('overview', models.TextField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('backdrop_url', models.URLField()),
                ('poster_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TasteTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now_add=True)),
                ('updated', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('teaser', models.TextField()),
                ('wikipedia', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now_add=True)),
                ('updated', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now=True)),
                ('priority', models.IntegerField(default=1)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff_api.Title', verbose_name='tconst')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
