# Generated by Django 2.2.12 on 2020-05-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0010_favouritegenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='nconst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='ff_api.Name'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='tconst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='ff_api.Title'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tconst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='ff_api.Title'),
        ),
    ]
