# Generated by Django 2.2.12 on 2020-05-14 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0011_auto_20200514_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='tconst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='ff_api.Title'),
        ),
    ]
