# Generated by Django 2.2.12 on 2020-05-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0011_moviedbtitle_recommendation_tastetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedbtitle',
            name='tconst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moviedb', to='ff_api.Title'),
        ),
        migrations.AddField(
            model_name='tastetitle',
            name='tconst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tastedb', to='ff_api.Title'),
        ),
    ]
