# Generated by Django 2.2.12 on 2020-05-15 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0012_auto_20200514_2322'),
        ('ff_api', '0013_rapidtitle'),
    ]

    operations = [
    ]
