# Generated by Django 2.2.12 on 2020-05-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0015_auto_20200515_0032'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourite',
            name='Unique favourite',
        ),
        migrations.RemoveConstraint(
            model_name='favouritegenre',
            name='Unique favourite genre',
        ),
        migrations.RemoveConstraint(
            model_name='seen',
            name='Unique seen',
        ),
        migrations.RemoveConstraint(
            model_name='watch',
            name='Unique watch',
        ),
    ]
