# Generated by Django 2.2.12 on 2020-05-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0016_auto_20200515_0035'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='Unique favourite'),
        ),
        migrations.AddConstraint(
            model_name='favouritegenre',
            constraint=models.UniqueConstraint(fields=('user', 'genre'), name='Unique favourite genre'),
        ),
        migrations.AddConstraint(
            model_name='seen',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='Unique seen'),
        ),
        migrations.AddConstraint(
            model_name='watch',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='Unique watch'),
        ),
    ]
