# Generated by Django 2.2.12 on 2020-05-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0018_auto_20200515_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tastetitle',
            name='teaser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tastetitle',
            name='wikipedia',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tastetitle',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
