# Generated by Django 2.2.12 on 2020-05-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0020_auto_20200515_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['user', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['primaryTitle', 'startYear', 'endYear']},
        ),
        migrations.AddField(
            model_name='seen',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seen',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='title',
            name='endYear',
            field=models.CharField(db_index=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='isAdult',
            field=models.CharField(db_index=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='title',
            name='runtimeMinutes',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='title',
            name='startYear',
            field=models.CharField(db_index=True, default='', max_length=4),
        ),
    ]
