# Generated by Django 2.2.12 on 2020-05-15 21:57

from django.db import migrations, models
import ff_api.fields.db
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0021_auto_20200515_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now_add=True)),
                ('updated', ff_api.fields.db.DateTimeFieldWithoutMicroseconds(auto_now=True)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('response', models.TextField(default='')),
            ],
        ),
    ]
