# Generated by Django 2.2.12 on 2020-05-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0023_auto_20200515_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='backdrop_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='poster_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='primaryTitle',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='backdrop_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='poster_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='primaryTitle',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seen',
            name='backdrop_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='seen',
            name='poster_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='seen',
            name='primaryTitle',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='backdrop_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='poster_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='primaryTitle',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
