# Generated by Django 2.2.12 on 2020-05-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0025_auto_20200516_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='cached_title_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='cached_title_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seen',
            name='cached_title_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watch',
            name='cached_title_data',
            field=models.BooleanField(default=False),
        ),
    ]
