# Generated by Django 2.2.12 on 2020-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_api', '0026_auto_20200516_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='image_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='name',
            name='moviedbid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
